name: Build Toolchain
on:
  push:
    branches:
      - main
    tags:
      - v**
  pull_request:
jobs:
  build:
    name: Build Toolchain
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target_arch: [aarch64, arm, i686, x86_64]
    steps:
    - name: Checkout Repo
      uses: actions/checkout@main
      with:
        path: ${{ github.workspace }}
    - name: Build Toolchain
      env:
        TOOLCHAIN_ARCH: ${{ matrix.target_arch }}
      run: |
        bash ./build.sh

  release:
    name: Create Github Release
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Fetch archives
        uses: actions/download-artifact@v3
        with:
          path: ./
      - name: Copy archives
        run: |
          cp newer-toolchain-*-${{ github.sha }}/*.tar.bz2 ./
      - name: Get tag
        id: tag
        uses: devops-actions/action-get-tag@v1
      - name: Publish GitHub release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "*.tar.bz2"
          file_glob: true
          release_name: "Android NDK toolchain version r13b with gcc" 
          tag: ${{ steps.tag.outputs.tag }}
